"""Shared library, CLI, and FastMCP HTTP server for EU Chirp 3 HD conversations."""

from tts_audio_conversation.logic import (
    EU_TRANSLATE_ENDPOINT,
    EU_TTS_ENDPOINT,
    MAX_BATCH_CHARS,
    AudioConversationService,
    AudioEncoding,
    ConversationMetadata,
    ConversationScript,
    ConversationTranslator,
    DialogueTurn,
    DownloadResult,
    JobNotFound,
    JobRecord,
    JobStatus,
    ScriptPayloadError,
    ScriptUploadResult,
    ScriptValidationResult,
    SynthesisCancelled,
    TranslateScriptResult,
    VoiceCatalogError,
    VoiceConfig,
    VoiceInfo,
    create_audio_conversation_service,
    create_audio_conversation_service_from_adc,
    create_script_template,
)

__all__ = [
    "AudioConversationService",
    "AudioEncoding",
    "ConversationMetadata",
    "ConversationScript",
    "ConversationTranslator",
    "DialogueTurn",
    "DownloadResult",
    "EU_TRANSLATE_ENDPOINT",
    "EU_TTS_ENDPOINT",
    "JobNotFound",
    "JobRecord",
    "JobStatus",
    "MAX_BATCH_CHARS",
    "ScriptPayloadError",
    "ScriptUploadResult",
    "ScriptValidationResult",
    "SynthesisCancelled",
    "TranslateScriptResult",
    "VoiceCatalogError",
    "VoiceConfig",
    "VoiceInfo",
    "create_audio_conversation_service",
    "create_audio_conversation_service_from_adc",
    "create_script_template",
]
